Feature#7.1 Update
wafflestudio18-5/team2-server pull request #19
Opened 2020-12-28 15:40 UTC by yuri-0415

merge 오류가 나서 수정했습니다

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        data = cache.get(cache_key)
cache를 사용하면 redis 관련해서 settings.py를 수정해야 하지 않을까요?

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +            else:
API문서에는 username이 Required, Non-Empty로 나와 있는데, 이 부분에 대한 점검이 필요할 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +                user = user.filter(username__icontains=username)
icontains와 exact 중 어떤 것이 적절할지 프론트엔드와 논의가 필요할 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        return Response(data)
401이나 404에 대한 처리가 필요할 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        return Response(self.get_serializer(user).data, status=status.HTTP_200_OK)
HTTP_200_OK가 default라서 굳이 명시할 필요는 없을 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        u = User.objects.get(id=user.id)
u가 결국 user인데, 다시 가져오시는 이유가 있나요?

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +                data = self.get_serializer(user, many=True).data
N+1 문제가 발생할 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        profile = UserProfile.objects.get(user=u)
`profile = request.user.userprofile`로 접근할 수도 있습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/views.py
> +        serializer.save()
`serializer.update`를 실행하고 `serializer.save`를 실행하면 update가 두 번 진행됩니다. 둘 중 하나만 남겨야 할 것 같습니다.

2020-12-29 17:13 UTC, gyusang commented on wadium/user/serializers.py
> +            'id',
이 `id`는 User의 id가 아니라 UserProfile의 id를 가져올텐데, 의도하신 게 맞나요?
API 문서에는 `id` 항목이 없습니다.

2020-12-29 17:24 UTC, gyusang commented on wadium/wadium/settings.py
> +    'allauth',
allauth를 추가하고자 하신다면 requirements.txt 수정 부탁드립니다.

2021-01-02 03:33 UTC, yuri-0415 commented
상규님 수정사항 반영했습니다!

2021-01-02 04:04 UTC, gyusang requested changes
Feature 7.1 <- main merge했습니다.
작업하기 전에 pull 부탁드립니다.

2021-01-02 04:04 UTC, gyusang commented on wadium/user/serializers.py
> +    facebook = serializers.CharField(source='user.userfacebook.facebook_sub', required=False)
이 부분은 추후에 MethodField가 될 예정인데, 임시로 CharField인 것인가요?
주석이 어떤 의미로 사용된 것인지 궁금해서 질문 드립니다.

2021-01-02 04:04 UTC, gyusang commented on wadium/user/views.py
> +        data = request.data.copy()
copy()가 필요한 이유가 있나요?

2021-01-02 04:04 UTC, gyusang commented on wadium/user/serializers.py
> +    email = serializers.CharField()
email은 Foreign Key 형태로 관리되고 있어 CharField()로 write할 수 없습니다.
이메일 관리 로직을 `update()`에서 구현하거나, 이 항목을 `read_only`로 설정해야 할 것 같습니다.

2021-01-02 04:04 UTC, gyusang commented on wadium/user/views.py
> +        return Response(self.get_serializer(user).data)
로그인하지 않은 유저가 요청할 경우 AnonymousUser에 대응되는 UserProfile 등이 없어 오류가 날 것 같습니다.
```python
if user.is_authenticated:
    return Response(self.get_serializer(user).data)
else:
    # return 404
```
등의 방법으로 예외 처리가 필요해 보입니다.

2021-01-02 04:11 UTC, gyusang commented on wadium/user/views.py
> +        users = self.get_queryset().filter(username__icontains=username)
`users = users.select_related('userprofile').prefetch_related('emails')` 등으로 N+1 문제를 완화하면 좋겠습니다.

2021-01-03 15:06 UTC, gyusang requested changes
list() 부분만 수정하면 될 것 같습니다!

2021-01-03 15:06 UTC, gyusang commented on wadium/user/views.py
> +        users = users.select_related('userprofile').prefetch_related('emails')
self.get_queryset().filter(...) 가 사라졌습니다 ㅜㅜ

2021-01-03 15:07 UTC, yuri-0415 commented on wadium/user/views.py
> +        users = users.select_related('userprofile').prefetch_related('emails')
앗 헐 미쳤나봐요ㅠㅠ

2021-01-03 15:08 UTC, gyusang commented on wadium/user/serializers.py
> +    email = serializers.CharField()
CharField에도 `read_only=True` 설정 부탁드립니다.

2021-01-03 15:08 UTC, gyusang requested changes

2021-01-03 15:08 UTC, gyusang commented on wadium/user/serializers.py
> +    email = serializers.CharField()
CharField에도 `read_only=True` 설정 부탁드립니다.

2021-01-03 15:39 UTC, gyusang approved these changes
일부 수정했습니다 :+1:

2021-01-03 15:40 UTC, yuri-0415 commented
> 일부 수정했습니다 👍

merge 하면 될까요?

2021-01-03 15:42 UTC, merged