Feature/#3
wafflestudio18-5/team2-server pull request #4
Opened 2020-11-27 11:59 UTC by symoon9

Pull Request for #3 
### story app에 model 만들기
(아직 만드는 중입니다...)

**[논의점]**
- uid 빼도 되는가?
- ImageField의 사용
    - `settings.py`에 `MEDIA_ROOT`, `MEDIA_URL` 정의해야함
- StoryBlock: 문단 순서 변수`paragraph`->`order`  

close #3

2020-11-27 12:07 UTC, gyusang commented
CI에 migrate가 포함되어 있지 않아 수정했습니다.
`python manage.py makemigrations story` 등으로 migration 파일을 만들면 통과될 것 같습니다.

2020-11-27 12:18 UTC, gyusang commented on wadium/story/models.py
> +    # uid  = models.CharField(max_length=100, null=False)
uid는 https://medium.com/@bdv111/aws-ec2에서-nginx로-react-앱-직접-배포하기-c1e09639171e 에서 c1e09639171e 처럼 글마다 있는 고유 문자열을 의미합니다. 따라서 연속된 숫자로 되어 있는 id와 다릅니다.

2020-11-27 12:27 UTC, gyusang requested changes

2020-11-27 12:27 UTC, gyusang commented on wadium/story/models.py
> +    writer_id = models.ForeignKey(User, null=False, related_name='story', on_delete=models.CASCADE)
user 한 명이 글을 여러 개 작성할 수 있으므로 `related_name='stories'`가 적절해 보입니다.

또한 필드명을 `writer`로 하면 DB에 `writer_id`로 저장되는 것을 의도하여 모델 다이어그램을 작성했는데 필드명을 `writer`로 바꾸는 것이 어떨까요?

2020-11-27 12:27 UTC, gyusang commented on wadium/story/models.py
> +    subtitle = models.CharField(max_length=100, null=True)
subtitle의 최대 글자수는 200자입니다.
또한 CharField는 `null=True` 등보다 `blank=True`, `blank=False`가 적절해 보입니다.

2020-11-28 06:34 UTC, symoon9 commented on wadium/story/models.py
> +    subtitle = models.CharField(max_length=100, null=True)
uid에 대해서도 적용될까요?

2020-12-14 10:48 UTC, symoon9 commented on wadium/story/models.py
> +    featured_image = models.PositiveSmallIntegerField(null=True) # put the order of the block that will be the feature image
미디엄에서 feature image 지정하는 방식이 글에 있는 이미지 중 하나를 선택하는 방식이었습니다. StoryBlock ForeignKey로 만드려고 했으나 python error가 생겨 order을 저장하고 그 block을 불러오는 방식으로 만들었습니다.

2020-12-14 10:50 UTC, symoon9 commented
@gyusang @yuri-0415 all done. 편하실 때 확인 부탁드립니다

2020-12-14 16:39 UTC, yuri-0415 commented
> @gyusang @yuri-0415 all done. 편하실 때 확인 부탁드립니다

확인했습니다!

2020-12-15 16:28 UTC, gyusang requested changes
확인했습니다.
몇 가지 unique constraint가 필요해 보입니다.

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    writer = models.ForeignKey(User, null=False, related_name='stories', on_delete=models.CASCADE)
`null=False`가 default인데 explicit하게 작성하는 게 나을까요?

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    title = models.CharField(max_length=100, blank=False)
`blank=False`가 default인데 explicit하게 작성하는 게 나을까요?

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    title = models.CharField(max_length=100, blank=False)
`title`에 db index 추가 부탁드립니다.

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    name = models.CharField(max_length=100, blank=False, unique=True)
`name`에 db index 추가 부탁드립니다.

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    read_at = models.DateTimeField(null=False)
(story, user)에 대한 unique constraint 설정 부탁드립니다.

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    # for image, content should be like this: "<img src = "./img/model1.png" width="70%">"
(story, order)에 대한 unique constraint 설정 부탁드립니다.

2020-12-15 16:28 UTC, gyusang commented on wadium/story/models.py
> +    featured_image = models.PositiveSmallIntegerField(null=True) # put the order of the block that will be the feature image
네 좋습니다!

2020-12-16 06:17 UTC, symoon9 commented on wadium/story/models.py
> +    writer = models.ForeignKey(User, null=False, related_name='stories', on_delete=models.CASCADE)
개인적으로는 필수인 field를 나중에 확인할 수 있도록 이렇게 작성하는 게 좋은 것 같습니다.

2020-12-16 06:20 UTC, symoon9 commented on wadium/story/models.py
> +    name = models.CharField(max_length=100, blank=False, unique=True)
`unique=True`로 설정하면 자동으로 index 생성하는 것으로 알고 있는데 따로 `db_index`설정이 필요한가요?

2020-12-16 08:53 UTC, gyusang commented on wadium/story/models.py
> +    name = models.CharField(max_length=100, blank=False, unique=True)
unique field라서 db_index가 필요 없겠네요!
제 실수입니다 ㅎㅎ

2020-12-16 17:34 UTC, gyusang requested changes
StoryTag에 (story, tag) unique_together 설정이 필요해 보입니다.

2020-12-16 17:34 UTC, gyusang commented on wadium/story/models.py
> +    subtitle = models.CharField(max_length=200, blank=True)
subtitle의 최대 길이가 140이었던 것 같은데, 200으로 하신 이유가 있나요?

2020-12-16 17:34 UTC, gyusang commented on wadium/story/models.py
> +    # for image, content should be like this: "<img src = "./img/model1.png" width="70%">"
예시에서 따옴표 "가 중복되어 사용되고 있습니다. `'<img src = "./img/model1.png" width="70%">'`으로 수정하면 좋을 것 같습니다.

2020-12-16 17:34 UTC, gyusang commented on wadium/story/models.py
> +    block_type = models.CharField(max_length=50, choices=BlockTypes)
block type이 두 가지인데 `max_length`를 5 정도로 해도 충분하지 않을까요?

2020-12-16 17:34 UTC, gyusang commented on wadium/story/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
(story, tag)에 unique constraint 추가 부탁드립니다.

2020-12-23 12:18 UTC, gyusang approved these changes
LGTM

2020-12-23 12:19 UTC, merged