Feature/#41
wafflestudio18-5/team2-server pull request #44
Opened 2021-01-06 17:16 UTC by yuri-0415

update GET user/pk/about, GET user/?username

2021-01-06 18:03 UTC, gyusang requested changes

2021-01-06 18:03 UTC, gyusang commented on wadium/user/serializers.py
>      bio = serializers.CharField(required=False)
`bio`에 `allow_blank=True`와 `max_length=140` 설정 부탁드립니다.

2021-01-06 18:03 UTC, gyusang commented on wadium/user/serializers.py
> +    username = serializers.CharField(source='user.username', read_only=True)
유저를 검색한 후 그 유저의 글을 받아오려면 /user/{id}/story/에 요청하기 위해 id가 필요해서, id를 함께 반환해야 할 것 같습니다.
`id = serializers.IntegerField(source='user.id', read_only=True)` 등으로 id를 UserProfileSerializer, UserSelfSerializer에 추가하는 것이 어떨까요?

2021-01-06 18:03 UTC, gyusang commented on wadium/user/serializers.py
>      name = serializers.CharField()
name에 `max_length=300` 설정 부탁드립니다.

2021-01-06 18:03 UTC, gyusang commented on wadium/user/views.py
> +            return Response(self.get_serializer(userprofiles, many=True).data)
username query에 pagination을 적용하기로 했었나요?

2021-01-06 18:04 UTC, gyusang commented on wadium/user/serializers.py
> +    username = serializers.CharField(source='user.username', read_only=True)
177번 줄에 추가했습니다.

2021-01-06 18:04 UTC, gyusang commented on wadium/user/serializers.py
>      bio = serializers.CharField(required=False)
추가했습니다.

2021-01-06 18:05 UTC, gyusang commented on wadium/user/serializers.py
>      name = serializers.CharField()
추가했습니다.

2021-01-07 10:31 UTC, yuri-0415 commented on wadium/user/views.py
> +            return Response(self.get_serializer(userprofiles, many=True).data)
5개를 기준으로 적용하기로 했던거 같긴 한데 정확하게 기억은 안나네요..

2021-01-07 10:31 UTC, yuri-0415 commented on wadium/user/views.py
> +            return Response(self.get_serializer(userprofiles, many=True).data)
오늘 야근이라 조금 늦어질것 같습니다

2021-01-07 10:56 UTC, gyusang commented on wadium/user/views.py
> +            return Response(self.get_serializer(userprofiles, many=True).data)
5개 정도면 될 것 같습니다.
야근 힘내세요!

2021-01-07 17:10 UTC, yuri-0415 commented
음 pagination 이런 식으로 하는게 아닌건가요😢

2021-01-07 19:55 UTC, gyusang approved these changes
> 음 pagination 이런 식으로 하는게 아닌건가요:cry:

page가 None인 경우까지 고려해서 완벽하게 만드셨네요!
다만 pagination의 경우 DRF에서 get_pagination_class 함수와 같은 기능을 제공하지 않아서, pagination_class나 paginate_queryset을 overrider해야 합니다. @property로  pagination_class를 overriding해 두었습니다.

2021-01-08 10:52 UTC, merged